# Generated by Django 5.2.14 on 2026-05-27 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'Ok'), ('PARSE_ERROR', 'Parse Error'), ('SKIPPED', 'Skipped')], max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('INGESTING', 'Ingesting'), ('NORMALIZING', 'Normalizing'), ('PENDING_REVIEW', 'Pending Review'), ('PARTIAL_FAILURE', 'Partial Failure'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_ref', models.CharField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(null=True)),
                ('flagged_count', models.IntegerField(null=True)),
                ('approved_count', models.IntegerField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('parser_version', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant')),
            ],
        ),
    ]
