# Generated by Django 5.2.14 on 2026-05-27 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=50)),
                ('activity_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('canonical_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('canonical_unit', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_id', models.CharField(blank=True, max_length=255)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('origin_iata', models.CharField(blank=True, max_length=10)),
                ('destination_iata', models.CharField(blank=True, max_length=10)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('distance_inferred', models.BooleanField(default=False)),
                ('source_system', models.CharField(max_length=100)),
                ('source_batch_ref', models.CharField(blank=True, max_length=255)),
                ('ingest_timestamp', models.DateTimeField()),
                ('parser_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('SUPERSEDED', 'Superseded')], default='PENDING_REVIEW', max_length=50)),
                ('anomaly_flags', models.JSONField(default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.batch')),
                ('raw_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='normalizati_tenant__91d465_idx'), models.Index(fields=['tenant', 'period_start', 'period_end'], name='normalizati_tenant__7af39a_idx'), models.Index(fields=['batch', 'status'], name='normalizati_batch_i_2a6e04_idx')],
            },
        ),
    ]
